apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-run-demo-app-1-dev
spec:
  template:
    spec:
      containers:
      - image: my-app-image
        ports:
        - name: http1
          containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: 1000m
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 80